<?php

use Illuminate\Database\Seeder;
use App\Models\Marca;
class MarcasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $marcas = [
            ['codigo' => 'BOR', 'descripcion' => 'BORDEN GELATINA', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'BOR', 'descripcion' => 'BORDEN MIX', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 0],
            ['codigo' => 'BOR', 'descripcion' => 'BORDEN LIGHT', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 0],
            ['codigo' => 'COU', 'descripcion' => 'COUNTRY FRESH', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 0],
            ['codigo' => 'OKY', 'descripcion' => 'OKY DRINK 1 LT', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO FRESH', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 0],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO LIGHT', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO PLUS', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO TEA', 'familia_id' => '12', 'iaba' => 1, 'nacional' => 0],
            ['codigo' => 'BUT', 'descripcion' => 'BUTTI', 'familia_id' => '9', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'TRI', 'descripcion' => 'TRIPLE CONCENTRADO', 'familia_id' => '9', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'OKY', 'descripcion' => 'OKY DRINK URUGUAY 2 LT', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 0],
            ['codigo' => 'REG', 'descripcion' => 'REGIMEL LIGHT', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO GELATINA', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'BAS', 'descripcion' => 'BASE ODORIFERA', 'familia_id' => '9', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'BAS', 'descripcion' => 'BASE COLORANTE', 'familia_id' => '9', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'BAS', 'descripcion' => 'BASE ESTABILIZADA', 'familia_id' => '9', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'FRU', 'descripcion' => 'FRUTA DESHIDRATADA VENTA', 'familia_id' => '9', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'BOR', 'descripcion' => 'BORDEN FLAN', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'SKY', 'descripcion' => 'SKYZZIT', 'familia_id' => '15', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'FRE', 'descripcion' => 'FRESCOLI', 'familia_id' => '15', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'SAB', 'descripcion' => 'SABORIZANTES LECHE', 'familia_id' => '16', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'NOV', 'descripcion' => 'NOVAFOODS', 'familia_id' => '24', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO BENNY', 'familia_id' => '18', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO BENNY POP', 'familia_id' => '18', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO 2 GO STICKS', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 0],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO FLAN', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'OKY', 'descripcion' => 'OKY GELATINA', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'SAB', 'descripcion' => 'SABOR. ART. P/HELADO', 'familia_id' => '9', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'REG', 'descripcion' => 'REGIMEL GELATINA ', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'REG', 'descripcion' => 'REGIMEL FLAN', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO SUGAR FREE FLAN', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO SUGAR FREE GELATINA', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'REG', 'descripcion' => 'REGIMEL CACAO', 'familia_id' => '18', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'REG', 'descripcion' => 'REGIMEL FRUCTOSA', 'familia_id' => '18', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'OKY', 'descripcion' => 'OKY DRINK 2 LT', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 0],
            ['codigo' => 'BOR', 'descripcion' => 'BORDEN INSTANT AID', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 0],
            ['codigo' => 'BOR', 'descripcion' => 'BORDEN INSTANT TEA', 'familia_id' => '12', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'OTR', 'descripcion' => 'OTROS', 'familia_id' => '16', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'PRO', 'descripcion' => 'PROM.12+1(PLUS+BENNY', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'PRO', 'descripcion' => 'PROM 10+1 PLUS/BENNY', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO ENERGY CHILE', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO ENERGY USA', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO ENERGY MX', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO ZERO', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO ENERGY CL RIST', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO ENERGY CL DISP', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'AND', 'descripcion' => 'ANDINOS SABORIZANTES', 'familia_id' => '18', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'OKY', 'descripcion' => 'OKY GEL PROM 7x5', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO PLUS V', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO TEA C', 'familia_id' => '12', 'iaba' => 1, 'nacional' => 0],
            ['codigo' => 'FRE', 'descripcion' => 'FRESCOLI POP', 'familia_id' => '15', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO PUDDING', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'PRO', 'descripcion' => 'PROM. T.ENERGY+SQUEE', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO PLUS BARBADOS', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO PLUS CHILE', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'OKY', 'descripcion' => 'OKY FLAN', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'OKY', 'descripcion' => 'OKY FLAN POP', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'OKY', 'descripcion' => 'OKY DRINK 8 LT', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'CAP', 'descripcion' => 'CAPUCCINO', 'familia_id' => '9', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'SLI', 'descripcion' => 'SLIM TONE', 'familia_id' => '9', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'OKY', 'descripcion' => 'OKY DRINK PAR 1 LT', 'familia_id' => '11', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'OKY', 'descripcion' => 'OKY DRINK PAR 2 LT', 'familia_id' => '11', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'OKY', 'descripcion' => 'OKY DRINK CUBA', 'familia_id' => '11', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'SQU', 'descripcion' => 'SQUEEZER TURBO ENERG POP', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'GAT', 'descripcion' => 'GATORADE', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO ENERGY', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'OKY', 'descripcion' => 'OKY DRINK', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'NOV', 'descripcion' => 'NOVAFOODS POP', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO 2 GO POP', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO 2 GO ICED TEA', 'familia_id' => '12', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'T. ', 'descripcion' => 'T. PLUS/ T.ZERO POP', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'S/L', 'descripcion' => 'S/LOGO POP', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO PLUS RISTRA', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'SGC', 'descripcion' => 'SGC POP', 'familia_id' => '16', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'KIG', 'descripcion' => 'KIGUSTOSO ', 'familia_id' => '11', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'SUP', 'descripcion' => 'SUPER CHOCO', 'familia_id' => '18', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'CAR', 'descripcion' => 'CARICIA GELATINA', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'VIV', 'descripcion' => 'VIVO', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'FRU', 'descripcion' => 'FRUCTUS', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'SPR', 'descripcion' => 'SPRIM', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'QUA', 'descripcion' => 'QUASAVISCO', 'familia_id' => '9', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO FLAN POP', 'familia_id' => '13', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'BOR', 'descripcion' => 'BORDEN MIX (ETIQUETA JAMAICA)', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 0],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO LIGHT GELATINA', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO LIGHT FLAN', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO PLUS BOLIVIA', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'OKY', 'descripcion' => 'OKY NATILLA', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'OKY', 'descripcion' => 'OKY MILK', 'familia_id' => '18', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'OKY', 'descripcion' => 'OKY DRINK CHILE 2 L', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'OKY', 'descripcion' => 'OKY DRINK CS20 2L', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'OKY', 'descripcion' => 'OKY DRINK CS10 1L', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'OKY', 'descripcion' => 'OKY DRINK AA20 2L', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'NAT', 'descripcion' => 'NATIV FOR LIFE', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO PLUS 7 L', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'MED', 'descripcion' => 'MEDALLA DE ORO TÉ', 'familia_id' => '12', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'MAL', 'descripcion' => 'MALTODEXTRINA GRANULADA', 'familia_id' => '9', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'MAR', 'descripcion' => 'MARIMBA FRESH', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'REN', 'descripcion' => 'RENOVA', 'familia_id' => '16', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TOT', 'descripcion' => 'TOTTUS', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'VIV', 'descripcion' => 'VIVALITE SUPLEMENTO', 'familia_id' => '16', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'VIV', 'descripcion' => 'VIVALITE SUPLEMENTO (MUESTRAS A GRANEL)', 'familia_id' => '16', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'VIT', 'descripcion' => 'VITAFLEX', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'OKY', 'descripcion' => 'OKY DRINK CS100 10L', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO ZERO FLAN', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO ZERO GELATINA', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'PAC', 'descripcion' => 'PACIFIC PUNCH', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 0],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO PLUS AA20 2L', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'VIV', 'descripcion' => 'VIVALITE PROTEIN', 'familia_id' => '16', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'VIV', 'descripcion' => 'VIVALITE ENERGY', 'familia_id' => '16', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'VIV', 'descripcion' => 'VIVALITE THICKENER', 'familia_id' => '16', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'LÍD', 'descripcion' => 'LÍDER ZERO', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'HEB', 'descripcion' => 'HEB', 'familia_id' => '11', 'iaba' => 0, 'nacional' => 0],
            ['codigo' => 'SIM', 'descripcion' => 'SIMI COLAGENO HIDROLIZADO', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'SAP', 'descripcion' => 'SAPORITI MEZCLA', 'familia_id' => '9', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'GAR', 'descripcion' => 'GARDEN HOUSE HIDROLÁGENO', 'familia_id' => '10', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'TUR', 'descripcion' => 'TURBO PLUS/TURBO ZERO (SAMPLING)', 'familia_id' => '10', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'VIV', 'descripcion' => 'VIVALITE THICKENER PLUS', 'familia_id' => '16', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'UP!', 'descripcion' => 'UP! SUPLEMENTO', 'familia_id' => '16', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'PRO', 'descripcion' => 'PROM OKY DRINK CS20 1L', 'familia_id' => '11', 'iaba' => 1, 'nacional' => 1],
            ['codigo' => 'PRO', 'descripcion' => 'PROM TURBO LIGHT GEL/FLAN', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 1],
            ['codigo' => 'PRO', 'descripcion' => 'PROM TURBO FLAN', 'familia_id' => '13', 'iaba' => 0, 'nacional' => 1]
        ];

        foreach ($marcas as $marca) {

            Marca::create($marca);
        }

    }
}
