<?php

use Illuminate\Database\Seeder;
use App\Models\Comercial\Comuna;

class ComunasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $comunas = [
            ['id' => 1,  'descripcion' => 'Arica', 'provincia_id' => 1],
            ['id' => 2,  'descripcion' => 'Camarones', 'provincia_id' => 1],
            ['id' => 3,  'descripcion' => 'Putre', 'provincia_id' => 2],
            ['id' => 4,  'descripcion' => 'General Lagos', 'provincia_id' => 2],
            ['id' => 5,  'descripcion' => 'Iquique', 'provincia_id' => 3],
            ['id' => 6,  'descripcion' => 'Alto Hospicio', 'provincia_id' => 3],
            ['id' => 7,  'descripcion' => 'Camiña', 'provincia_id' => 4],
            ['id' => 8,  'descripcion' => 'Colchane', 'provincia_id' => 4],
            ['id' => 9,  'descripcion' => 'Huara', 'provincia_id' => 4],
            ['id' => 10,  'descripcion' => 'Pica', 'provincia_id' => 4],
            ['id' => 11,  'descripcion' => 'Pozo Almonte', 'provincia_id' => 4],
            ['id' => 12,  'descripcion' => 'Antofagasta', 'provincia_id' => 5],
            ['id' => 13,  'descripcion' => 'Mejillones', 'provincia_id' => 5],
            ['id' => 14,  'descripcion' => 'Sierra Gorda', 'provincia_id' => 5],
            ['id' => 15,  'descripcion' => 'Taltal', 'provincia_id' => 5],
            ['id' => 16,  'descripcion' => 'Calama', 'provincia_id' => 6],
            ['id' => 17,  'descripcion' => 'Ollagüe', 'provincia_id' => 6],
            ['id' => 18,  'descripcion' => 'San Pedro de Atacama', 'provincia_id' => 6],
            ['id' => 19,  'descripcion' => 'Tocopilla', 'provincia_id' => 7],
            ['id' => 20,  'descripcion' => 'María Elena', 'provincia_id' => 7],
            ['id' => 21,  'descripcion' => 'Copiapó', 'provincia_id' => 8],
            ['id' => 22,  'descripcion' => 'Caldera', 'provincia_id' => 8],
            ['id' => 23,  'descripcion' => 'Tierra Amarilla', 'provincia_id' => 8],
            ['id' => 24,  'descripcion' => 'Chañaral', 'provincia_id' => 9],
            ['id' => 25,  'descripcion' => 'Diego de Almagro', 'provincia_id' => 9],
            ['id' => 26,  'descripcion' => 'Vallenar', 'provincia_id' => 10],
            ['id' => 27,  'descripcion' => 'Alto del Carmen', 'provincia_id' => 10],
            ['id' => 28,  'descripcion' => 'Freirina', 'provincia_id' => 10],
            ['id' => 29,  'descripcion' => 'Huasco', 'provincia_id' => 10],
            ['id' => 30,  'descripcion' => 'La Serena', 'provincia_id' => 11],
            ['id' => 31,  'descripcion' => 'Coquimbo', 'provincia_id' => 11],
            ['id' => 32,  'descripcion' => 'Andacollo', 'provincia_id' => 11],
            ['id' => 33,  'descripcion' => 'La Higuera', 'provincia_id' => 11],
            ['id' => 34,  'descripcion' => 'Paiguano', 'provincia_id' => 11],
            ['id' => 35,  'descripcion' => 'Vicuña', 'provincia_id' => 11],
            ['id' => 36,  'descripcion' => 'Illapel', 'provincia_id' => 12],
            ['id' => 37,  'descripcion' => 'Canela', 'provincia_id' => 12],
            ['id' => 38,  'descripcion' => 'Los Vilos', 'provincia_id' => 12],
            ['id' => 39,  'descripcion' => 'Salamanca', 'provincia_id' => 12],
            ['id' => 40,  'descripcion' => 'Ovalle', 'provincia_id' => 13],
            ['id' => 41,  'descripcion' => 'Combarbalá', 'provincia_id' => 13],
            ['id' => 42,  'descripcion' => 'Monte Patria', 'provincia_id' => 13],
            ['id' => 43,  'descripcion' => 'Punitaqui', 'provincia_id' => 13],
            ['id' => 44,  'descripcion' => 'Río Hurtado', 'provincia_id' => 13],
            ['id' => 45,  'descripcion' => 'Valparaíso', 'provincia_id' => 14],
            ['id' => 46,  'descripcion' => 'Casablanca', 'provincia_id' => 14],
            ['id' => 47,  'descripcion' => 'Concón', 'provincia_id' => 14],
            ['id' => 48,  'descripcion' => 'Juan Fernández', 'provincia_id' => 14],
            ['id' => 49,  'descripcion' => 'Puchuncaví', 'provincia_id' => 14],
            ['id' => 50,  'descripcion' => 'Quintero', 'provincia_id' => 14],
            ['id' => 51,  'descripcion' => 'Viña del Mar', 'provincia_id' => 14],
            ['id' => 52,  'descripcion' => 'Isla  de Pascua', 'provincia_id' => 15],
            ['id' => 53,  'descripcion' => 'Los Andes', 'provincia_id' => 16],
            ['id' => 54,  'descripcion' => 'Calle Larga', 'provincia_id' => 16],
            ['id' => 55,  'descripcion' => 'Rinconada', 'provincia_id' => 16],
            ['id' => 56,  'descripcion' => 'San Esteban', 'provincia_id' => 16],
            ['id' => 57,  'descripcion' => 'La Ligua', 'provincia_id' => 17],
            ['id' => 58,  'descripcion' => 'Cabildo', 'provincia_id' => 17],
            ['id' => 59,  'descripcion' => 'Papudo', 'provincia_id' => 17],
            ['id' => 60,  'descripcion' => 'Petorca', 'provincia_id' => 17],
            ['id' => 61,  'descripcion' => 'Zapallar', 'provincia_id' => 17],
            ['id' => 62,  'descripcion' => 'Quillota', 'provincia_id' => 18],
            ['id' => 63,  'descripcion' => 'Calera', 'provincia_id' => 18],
            ['id' => 64,  'descripcion' => 'Hijuelas', 'provincia_id' => 18],
            ['id' => 65,  'descripcion' => 'La Cruz', 'provincia_id' => 18],
            ['id' => 66,  'descripcion' => 'Nogales', 'provincia_id' => 18],
            ['id' => 67,  'descripcion' => 'San Antonio', 'provincia_id' => 19],
            ['id' => 68,  'descripcion' => 'Algarrobo', 'provincia_id' => 19],
            ['id' => 69,  'descripcion' => 'Cartagena', 'provincia_id' => 19],
            ['id' => 70,  'descripcion' => 'El Quisco', 'provincia_id' => 19],
            ['id' => 71,  'descripcion' => 'El Tabo', 'provincia_id' => 19],
            ['id' => 72,  'descripcion' => 'Santo Domingo', 'provincia_id' => 19],
            ['id' => 73,  'descripcion' => 'San Felipe', 'provincia_id' => 20],
            ['id' => 74,  'descripcion' => 'Catemu', 'provincia_id' => 20],
            ['id' => 75,  'descripcion' => 'Llaillay', 'provincia_id' => 20],
            ['id' => 76,  'descripcion' => 'Panquehue', 'provincia_id' => 20],
            ['id' => 77,  'descripcion' => 'Putaendo', 'provincia_id' => 20],
            ['id' => 78,  'descripcion' => 'Santa María', 'provincia_id' => 20],
            ['id' => 79,  'descripcion' => 'Quilpué', 'provincia_id' => 21],
            ['id' => 80,  'descripcion' => 'Villa Alemana', 'provincia_id' => 21],
            ['id' => 81,  'descripcion' => 'Limache', 'provincia_id' => 21],
            ['id' => 82,  'descripcion' => 'Olmué', 'provincia_id' => 21],
            ['id' => 83,  'descripcion' => 'Rancagua', 'provincia_id' => 22],
            ['id' => 84,  'descripcion' => 'Codegua', 'provincia_id' => 22],
            ['id' => 85,  'descripcion' => 'Coinco', 'provincia_id' => 22],
            ['id' => 86,  'descripcion' => 'Coltauco', 'provincia_id' => 22],
            ['id' => 87,  'descripcion' => 'Doñihue', 'provincia_id' => 22],
            ['id' => 88,  'descripcion' => 'Graneros', 'provincia_id' => 22],
            ['id' => 89,  'descripcion' => 'Las Cabras', 'provincia_id' => 22],
            ['id' => 90,  'descripcion' => 'Machalí', 'provincia_id' => 22],
            ['id' => 91,  'descripcion' => 'Malloa', 'provincia_id' => 22],
            ['id' => 92,  'descripcion' => 'Mostazal', 'provincia_id' => 22],
            ['id' => 93,  'descripcion' => 'Olivar', 'provincia_id' => 22],
            ['id' => 94,  'descripcion' => 'Peumo', 'provincia_id' => 22],
            ['id' => 95,  'descripcion' => 'Pichidegua', 'provincia_id' => 22],
            ['id' => 96,  'descripcion' => 'Quinta de Tilcoco', 'provincia_id' => 22],
            ['id' => 97,  'descripcion' => 'Rengo', 'provincia_id' => 22],
            ['id' => 98,  'descripcion' => 'Requínoa', 'provincia_id' => 22],
            ['id' => 99,  'descripcion' => 'San Vicente', 'provincia_id' => 22],
            ['id' => 100,  'descripcion' => 'Pichilemu', 'provincia_id' => 23],
            ['id' => 101,  'descripcion' => 'La Estrella', 'provincia_id' => 23],
            ['id' => 102,  'descripcion' => 'Litueche', 'provincia_id' => 23],
            ['id' => 103,  'descripcion' => 'Marchihue', 'provincia_id' => 23],
            ['id' => 104,  'descripcion' => 'Navidad', 'provincia_id' => 23],
            ['id' => 105,  'descripcion' => 'Paredones', 'provincia_id' => 23],
            ['id' => 106,  'descripcion' => 'San Fernando', 'provincia_id' => 24],
            ['id' => 107,  'descripcion' => 'Chépica', 'provincia_id' => 24],
            ['id' => 108,  'descripcion' => 'Chimbarongo', 'provincia_id' => 24],
            ['id' => 109,  'descripcion' => 'Lolol', 'provincia_id' => 24],
            ['id' => 110,  'descripcion' => 'Nancagua', 'provincia_id' => 24],
            ['id' => 111,  'descripcion' => 'Palmilla', 'provincia_id' => 24],
            ['id' => 112,  'descripcion' => 'Peralillo', 'provincia_id' => 24],
            ['id' => 113,  'descripcion' => 'Placilla', 'provincia_id' => 24],
            ['id' => 114,  'descripcion' => 'Pumanque', 'provincia_id' => 24],
            ['id' => 115,  'descripcion' => 'Santa Cruz', 'provincia_id' => 24],
            ['id' => 116,  'descripcion' => 'Talca', 'provincia_id' => 25],
            ['id' => 117,  'descripcion' => 'Constitución', 'provincia_id' => 25],
            ['id' => 118,  'descripcion' => 'Curepto', 'provincia_id' => 25],
            ['id' => 119,  'descripcion' => 'Empedrado', 'provincia_id' => 25],
            ['id' => 120,  'descripcion' => 'Maule', 'provincia_id' => 25],
            ['id' => 121,  'descripcion' => 'Pelarco', 'provincia_id' => 25],
            ['id' => 122,  'descripcion' => 'Pencahue', 'provincia_id' => 25],
            ['id' => 123,  'descripcion' => 'Río Claro', 'provincia_id' => 25],
            ['id' => 124,  'descripcion' => 'San Clemente', 'provincia_id' => 25],
            ['id' => 125,  'descripcion' => 'San Rafael', 'provincia_id' => 25],
            ['id' => 126,  'descripcion' => 'Cauquenes', 'provincia_id' => 26],
            ['id' => 127,  'descripcion' => 'Chanco', 'provincia_id' => 26],
            ['id' => 128,  'descripcion' => 'Pelluhue', 'provincia_id' => 26],
            ['id' => 129,  'descripcion' => 'Curicó', 'provincia_id' => 27],
            ['id' => 130,  'descripcion' => 'Hualañé', 'provincia_id' => 27],
            ['id' => 131,  'descripcion' => 'Licantén', 'provincia_id' => 27],
            ['id' => 132,  'descripcion' => 'Molina', 'provincia_id' => 27],
            ['id' => 133,  'descripcion' => 'Rauco', 'provincia_id' => 27],
            ['id' => 134,  'descripcion' => 'Romeral', 'provincia_id' => 27],
            ['id' => 135,  'descripcion' => 'Sagrada Familia', 'provincia_id' => 27],
            ['id' => 136,  'descripcion' => 'Teno', 'provincia_id' => 27],
            ['id' => 137,  'descripcion' => 'Vichuquén', 'provincia_id' => 27],
            ['id' => 138,  'descripcion' => 'Linares', 'provincia_id' => 28],
            ['id' => 139,  'descripcion' => 'Colbún', 'provincia_id' => 28],
            ['id' => 140,  'descripcion' => 'Longaví', 'provincia_id' => 28],
            ['id' => 141,  'descripcion' => 'Parral', 'provincia_id' => 28],
            ['id' => 142,  'descripcion' => 'Retiro', 'provincia_id' => 28],
            ['id' => 143,  'descripcion' => 'San Javier', 'provincia_id' => 28],
            ['id' => 144,  'descripcion' => 'Villa Alegre', 'provincia_id' => 28],
            ['id' => 145,  'descripcion' => 'Yerbas Buenas', 'provincia_id' => 28],
            ['id' => 146,  'descripcion' => 'Concepción', 'provincia_id' => 29],
            ['id' => 147,  'descripcion' => 'Coronel', 'provincia_id' => 29],
            ['id' => 148,  'descripcion' => 'Chiguayante', 'provincia_id' => 29],
            ['id' => 149,  'descripcion' => 'Florida', 'provincia_id' => 29],
            ['id' => 150,  'descripcion' => 'Hualqui', 'provincia_id' => 29],
            ['id' => 151,  'descripcion' => 'Lota', 'provincia_id' => 29],
            ['id' => 152,  'descripcion' => 'Penco', 'provincia_id' => 29],
            ['id' => 153,  'descripcion' => 'San Pedro de la Paz', 'provincia_id' => 29],
            ['id' => 154,  'descripcion' => 'Santa Juana', 'provincia_id' => 29],
            ['id' => 155,  'descripcion' => 'Talcahuano', 'provincia_id' => 29],
            ['id' => 156,  'descripcion' => 'Tomé', 'provincia_id' => 29],
            ['id' => 157,  'descripcion' => 'Hualpén', 'provincia_id' => 29],
            ['id' => 158,  'descripcion' => 'Lebu', 'provincia_id' => 30],
            ['id' => 159,  'descripcion' => 'Arauco', 'provincia_id' => 30],
            ['id' => 160,  'descripcion' => 'Cañete', 'provincia_id' => 30],
            ['id' => 161,  'descripcion' => 'Contulmo', 'provincia_id' => 30],
            ['id' => 162,  'descripcion' => 'Curanilahue', 'provincia_id' => 30],
            ['id' => 163,  'descripcion' => 'Los Álamos', 'provincia_id' => 30],
            ['id' => 164,  'descripcion' => 'Tirúa', 'provincia_id' => 30],
            ['id' => 165,  'descripcion' => 'Los Ángeles', 'provincia_id' => 31],
            ['id' => 166,  'descripcion' => 'Antuco', 'provincia_id' => 31],
            ['id' => 167,  'descripcion' => 'Cabrero', 'provincia_id' => 31],
            ['id' => 168,  'descripcion' => 'Laja', 'provincia_id' => 31],
            ['id' => 169,  'descripcion' => 'Mulchén', 'provincia_id' => 31],
            ['id' => 170,  'descripcion' => 'Nacimiento', 'provincia_id' => 31],
            ['id' => 171,  'descripcion' => 'Negrete', 'provincia_id' => 31],
            ['id' => 172,  'descripcion' => 'Quilaco', 'provincia_id' => 31],
            ['id' => 173,  'descripcion' => 'Quilleco', 'provincia_id' => 31],
            ['id' => 174,  'descripcion' => 'San Rosendo', 'provincia_id' => 31],
            ['id' => 175,  'descripcion' => 'Santa Bárbara', 'provincia_id' => 31],
            ['id' => 176,  'descripcion' => 'Tucapel', 'provincia_id' => 31],
            ['id' => 177,  'descripcion' => 'Yumbel', 'provincia_id' => 31],
            ['id' => 178,  'descripcion' => 'Alto Biobío', 'provincia_id' => 31],
            ['id' => 179,  'descripcion' => 'Chillán', 'provincia_id' => 32],
            ['id' => 180,  'descripcion' => 'Bulnes', 'provincia_id' => 32],
            ['id' => 181,  'descripcion' => 'Cobquecura', 'provincia_id' => 32],
            ['id' => 182,  'descripcion' => 'Coelemu', 'provincia_id' => 32],
            ['id' => 183,  'descripcion' => 'Coihueco', 'provincia_id' => 32],
            ['id' => 184,  'descripcion' => 'Chillán Viejo', 'provincia_id' => 32],
            ['id' => 185,  'descripcion' => 'El Carmen', 'provincia_id' => 32],
            ['id' => 186,  'descripcion' => 'Ninhue', 'provincia_id' => 32],
            ['id' => 187,  'descripcion' => 'Ñiquén', 'provincia_id' => 32],
            ['id' => 188,  'descripcion' => 'Pemuco', 'provincia_id' => 32],
            ['id' => 189,  'descripcion' => 'Pinto', 'provincia_id' => 32],
            ['id' => 190,  'descripcion' => 'Portezuelo', 'provincia_id' => 32],
            ['id' => 191,  'descripcion' => 'Quillón', 'provincia_id' => 32],
            ['id' => 192,  'descripcion' => 'Quirihue', 'provincia_id' => 32],
            ['id' => 193,  'descripcion' => 'Ránquil', 'provincia_id' => 32],
            ['id' => 194,  'descripcion' => 'San Carlos', 'provincia_id' => 32],
            ['id' => 195,  'descripcion' => 'San Fabián', 'provincia_id' => 32],
            ['id' => 196,  'descripcion' => 'San Ignacio', 'provincia_id' => 32],
            ['id' => 197,  'descripcion' => 'San Nicolás', 'provincia_id' => 32],
            ['id' => 198,  'descripcion' => 'Treguaco', 'provincia_id' => 32],
            ['id' => 199,  'descripcion' => 'Yungay', 'provincia_id' => 32],
            ['id' => 200,  'descripcion' => 'Temuco', 'provincia_id' => 33],
            ['id' => 201,  'descripcion' => 'Carahue', 'provincia_id' => 33],
            ['id' => 202,  'descripcion' => 'Cunco', 'provincia_id' => 33],
            ['id' => 203,  'descripcion' => 'Curarrehue', 'provincia_id' => 33],
            ['id' => 204,  'descripcion' => 'Freire', 'provincia_id' => 33],
            ['id' => 205,  'descripcion' => 'Galvarino', 'provincia_id' => 33],
            ['id' => 206,  'descripcion' => 'Gorbea', 'provincia_id' => 33],
            ['id' => 207,  'descripcion' => 'Lautaro', 'provincia_id' => 33],
            ['id' => 208,  'descripcion' => 'Loncoche', 'provincia_id' => 33],
            ['id' => 209,  'descripcion' => 'Melipeuco', 'provincia_id' => 33],
            ['id' => 210,  'descripcion' => 'Nueva Imperial', 'provincia_id' => 33],
            ['id' => 211,  'descripcion' => 'Padre Las Casas', 'provincia_id' => 33],
            ['id' => 212,  'descripcion' => 'Perquenco', 'provincia_id' => 33],
            ['id' => 213,  'descripcion' => 'Pitrufquén', 'provincia_id' => 33],
            ['id' => 214,  'descripcion' => 'Pucón', 'provincia_id' => 33],
            ['id' => 215,  'descripcion' => 'Saavedra', 'provincia_id' => 33],
            ['id' => 216,  'descripcion' => 'Teodoro Schmidt', 'provincia_id' => 33],
            ['id' => 217,  'descripcion' => 'Toltén', 'provincia_id' => 33],
            ['id' => 218,  'descripcion' => 'Vilcún', 'provincia_id' => 33],
            ['id' => 219,  'descripcion' => 'Villarrica', 'provincia_id' => 33],
            ['id' => 220,  'descripcion' => 'Cholchol', 'provincia_id' => 33],
            ['id' => 221,  'descripcion' => 'Angol', 'provincia_id' => 34],
            ['id' => 222,  'descripcion' => 'Collipulli', 'provincia_id' => 34],
            ['id' => 223,  'descripcion' => 'Curacautín', 'provincia_id' => 34],
            ['id' => 224,  'descripcion' => 'Ercilla', 'provincia_id' => 34],
            ['id' => 225,  'descripcion' => 'Lonquimay', 'provincia_id' => 34],
            ['id' => 226,  'descripcion' => 'Los Sauces', 'provincia_id' => 34],
            ['id' => 227,  'descripcion' => 'Lumaco', 'provincia_id' => 34],
            ['id' => 228,  'descripcion' => 'Purén', 'provincia_id' => 34],
            ['id' => 229,  'descripcion' => 'Renaico', 'provincia_id' => 34],
            ['id' => 230,  'descripcion' => 'Traiguén', 'provincia_id' => 34],
            ['id' => 231,  'descripcion' => 'Victoria', 'provincia_id' => 34],
            ['id' => 232,  'descripcion' => 'Valdivia', 'provincia_id' => 35],
            ['id' => 233,  'descripcion' => 'Corral', 'provincia_id' => 35],
            ['id' => 234,  'descripcion' => 'Lanco', 'provincia_id' => 35],
            ['id' => 235,  'descripcion' => 'Los Lagos', 'provincia_id' => 35],
            ['id' => 236,  'descripcion' => 'Máfil', 'provincia_id' => 35],
            ['id' => 237,  'descripcion' => 'Mariquina', 'provincia_id' => 35],
            ['id' => 238,  'descripcion' => 'Paillaco', 'provincia_id' => 35],
            ['id' => 239,  'descripcion' => 'Panguipulli', 'provincia_id' => 35],
            ['id' => 240,  'descripcion' => 'Futrono', 'provincia_id' => 36],
            ['id' => 241,  'descripcion' => 'La Unión', 'provincia_id' => 36],
            ['id' => 242,  'descripcion' => 'Lago Ranco', 'provincia_id' => 36],
            ['id' => 243,  'descripcion' => 'Río Bueno', 'provincia_id' => 36],
            ['id' => 244,  'descripcion' => 'Puerto Montt', 'provincia_id' => 37],
            ['id' => 245,  'descripcion' => 'Calbuco', 'provincia_id' => 37],
            ['id' => 246,  'descripcion' => 'Cochamó', 'provincia_id' => 37],
            ['id' => 247,  'descripcion' => 'Fresia', 'provincia_id' => 37],
            ['id' => 248,  'descripcion' => 'Frutillar', 'provincia_id' => 37],
            ['id' => 249,  'descripcion' => 'Los Muermos', 'provincia_id' => 37],
            ['id' => 250,  'descripcion' => 'Llanquihue', 'provincia_id' => 37],
            ['id' => 251,  'descripcion' => 'Maullín', 'provincia_id' => 37],
            ['id' => 252,  'descripcion' => 'Puerto Varas', 'provincia_id' => 37],
            ['id' => 253,  'descripcion' => 'Castro', 'provincia_id' => 38],
            ['id' => 254,  'descripcion' => 'Ancud', 'provincia_id' => 38],
            ['id' => 255,  'descripcion' => 'Chonchi', 'provincia_id' => 38],
            ['id' => 256,  'descripcion' => 'Curaco de Vélez', 'provincia_id' => 38],
            ['id' => 257,  'descripcion' => 'Dalcahue', 'provincia_id' => 38],
            ['id' => 258,  'descripcion' => 'Puqueldón', 'provincia_id' => 38],
            ['id' => 259,  'descripcion' => 'Queilén', 'provincia_id' => 38],
            ['id' => 260,  'descripcion' => 'Quellón', 'provincia_id' => 38],
            ['id' => 261,  'descripcion' => 'Quemchi', 'provincia_id' => 38],
            ['id' => 262,  'descripcion' => 'Quinchao', 'provincia_id' => 38],
            ['id' => 263,  'descripcion' => 'Osorno', 'provincia_id' => 39],
            ['id' => 264,  'descripcion' => 'Puerto Octay', 'provincia_id' => 39],
            ['id' => 265,  'descripcion' => 'Purranque', 'provincia_id' => 39],
            ['id' => 266,  'descripcion' => 'Puyehue', 'provincia_id' => 39],
            ['id' => 267,  'descripcion' => 'Río Negro', 'provincia_id' => 39],
            ['id' => 268,  'descripcion' => 'San Juan de la Costa', 'provincia_id' => 39],
            ['id' => 269,  'descripcion' => 'San Pablo', 'provincia_id' => 39],
            ['id' => 270,  'descripcion' => 'Chaitén', 'provincia_id' => 40],
            ['id' => 271,  'descripcion' => 'Futaleufú', 'provincia_id' => 40],
            ['id' => 272,  'descripcion' => 'Hualaihué', 'provincia_id' => 40],
            ['id' => 273,  'descripcion' => 'Palena', 'provincia_id' => 40],
            ['id' => 274,  'descripcion' => 'Coihaique', 'provincia_id' => 41],
            ['id' => 275,  'descripcion' => 'Lago Verde', 'provincia_id' => 41],
            ['id' => 276,  'descripcion' => 'Aisén', 'provincia_id' => 42],
            ['id' => 277,  'descripcion' => 'Cisnes', 'provincia_id' => 42],
            ['id' => 278,  'descripcion' => 'Guaitecas', 'provincia_id' => 42],
            ['id' => 279,  'descripcion' => 'Cochrane', 'provincia_id' => 43],
            ['id' => 280,  'descripcion' => 'O`Higgins', 'provincia_id' => 43],
            ['id' => 281,  'descripcion' => 'Tortel', 'provincia_id' => 43],
            ['id' => 282,  'descripcion' => 'Chile Chico', 'provincia_id' => 44],
            ['id' => 283,  'descripcion' => 'Río Ibáñez', 'provincia_id' => 44],
            ['id' => 284,  'descripcion' => 'Punta Arenas', 'provincia_id' => 45],
            ['id' => 285,  'descripcion' => 'Laguna Blanca', 'provincia_id' => 45],
            ['id' => 286,  'descripcion' => 'Río Verde', 'provincia_id' => 45],
            ['id' => 287,  'descripcion' => 'San Gregorio', 'provincia_id' => 45],
            ['id' => 288,  'descripcion' => 'Cabo de Hornos', 'provincia_id' => 46],
            ['id' => 289,  'descripcion' => 'Antártica', 'provincia_id' => 46],
            ['id' => 290,  'descripcion' => 'Porvenir', 'provincia_id' => 47],
            ['id' => 291,  'descripcion' => 'Primavera', 'provincia_id' => 47],
            ['id' => 292,  'descripcion' => 'Timaukel', 'provincia_id' => 47],
            ['id' => 293,  'descripcion' => 'Natales', 'provincia_id' => 48],
            ['id' => 294,  'descripcion' => 'Torres del Paine', 'provincia_id' => 48],
            ['id' => 295,  'descripcion' => 'Santiago', 'provincia_id' => 49],
            ['id' => 296,  'descripcion' => 'Cerrillos', 'provincia_id' => 49],
            ['id' => 297,  'descripcion' => 'Cerro Navia', 'provincia_id' => 49],
            ['id' => 298,  'descripcion' => 'Conchalí', 'provincia_id' => 49],
            ['id' => 299,  'descripcion' => 'El Bosque', 'provincia_id' => 49],
            ['id' => 300,  'descripcion' => 'Estación Central', 'provincia_id' => 49],
            ['id' => 301,  'descripcion' => 'Huechuraba', 'provincia_id' => 49],
            ['id' => 302,  'descripcion' => 'Independencia', 'provincia_id' => 49],
            ['id' => 303,  'descripcion' => 'La Cisterna', 'provincia_id' => 49],
            ['id' => 304,  'descripcion' => 'La Florida', 'provincia_id' => 49],
            ['id' => 305,  'descripcion' => 'La Granja', 'provincia_id' => 49],
            ['id' => 306,  'descripcion' => 'La Pintana', 'provincia_id' => 49],
            ['id' => 307,  'descripcion' => 'La Reina', 'provincia_id' => 49],
            ['id' => 308,  'descripcion' => 'Las Condes', 'provincia_id' => 49],
            ['id' => 309,  'descripcion' => 'Lo Barnechea', 'provincia_id' => 49],
            ['id' => 310,  'descripcion' => 'Lo Espejo', 'provincia_id' => 49],
            ['id' => 311,  'descripcion' => 'Lo Prado', 'provincia_id' => 49],
            ['id' => 312,  'descripcion' => 'Macul', 'provincia_id' => 49],
            ['id' => 313,  'descripcion' => 'Maipú', 'provincia_id' => 49],
            ['id' => 314,  'descripcion' => 'Ñuñoa', 'provincia_id' => 49],
            ['id' => 315,  'descripcion' => 'Pedro Aguirre Cerda', 'provincia_id' => 49],
            ['id' => 316,  'descripcion' => 'Peñalolén', 'provincia_id' => 49],
            ['id' => 317,  'descripcion' => 'Providencia', 'provincia_id' => 49],
            ['id' => 318,  'descripcion' => 'Pudahuel', 'provincia_id' => 49],
            ['id' => 319,  'descripcion' => 'Quilicura', 'provincia_id' => 49],
            ['id' => 320,  'descripcion' => 'Quinta Normal', 'provincia_id' => 49],
            ['id' => 321,  'descripcion' => 'Recoleta', 'provincia_id' => 49],
            ['id' => 322,  'descripcion' => 'Renca', 'provincia_id' => 49],
            ['id' => 323,  'descripcion' => 'San Joaquín', 'provincia_id' => 49],
            ['id' => 324,  'descripcion' => 'San Miguel', 'provincia_id' => 49],
            ['id' => 325,  'descripcion' => 'San Ramón', 'provincia_id' => 49],
            ['id' => 326,  'descripcion' => 'Vitacura', 'provincia_id' => 49],
            ['id' => 327,  'descripcion' => 'Puente Alto', 'provincia_id' => 50],
            ['id' => 328,  'descripcion' => 'Pirque', 'provincia_id' => 50],
            ['id' => 329,  'descripcion' => 'San José de Maipo', 'provincia_id' => 50],
            ['id' => 330,  'descripcion' => 'Colina', 'provincia_id' => 51],
            ['id' => 331,  'descripcion' => 'Lampa', 'provincia_id' => 51],
            ['id' => 332,  'descripcion' => 'Tiltil', 'provincia_id' => 51],
            ['id' => 333,  'descripcion' => 'San Bernardo', 'provincia_id' => 52],
            ['id' => 334,  'descripcion' => 'Buin', 'provincia_id' => 52],
            ['id' => 335,  'descripcion' => 'Calera de Tango', 'provincia_id' => 52],
            ['id' => 336,  'descripcion' => 'Paine', 'provincia_id' => 52],
            ['id' => 337,  'descripcion' => 'Melipilla', 'provincia_id' => 53],
            ['id' => 338,  'descripcion' => 'Alhué', 'provincia_id' => 53],
            ['id' => 339,  'descripcion' => 'Curacaví', 'provincia_id' => 53],
            ['id' => 340,  'descripcion' => 'María Pinto', 'provincia_id' => 53],
            ['id' => 341,  'descripcion' => 'San Pedro', 'provincia_id' => 53],
            ['id' => 342,  'descripcion' => 'Talagante', 'provincia_id' => 54],
            ['id' => 343,  'descripcion' => 'El Monte', 'provincia_id' => 54],
            ['id' => 344,  'descripcion' => 'Isla de Maipo', 'provincia_id' => 54],
            ['id' => 345,  'descripcion' => 'Padre Hurtado', 'provincia_id' => 54],
            ['id' => 346,  'descripcion' => 'Peñaflor', 'provincia_id' => 54],
        ];

        foreach ($comunas as $comuna) {

            Comuna::create($comuna);
        }
    }
}
