<?php

use Illuminate\Database\Seeder;
use App\Models\Comercial\Pais;

class PaisTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $paises = [
        [ 'nombre' => 'Afganistán' , 'capital' => 'Kabul', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Albania' , 'capital' => 'Tirana', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Alemania' , 'capital' => 'Berlín', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Andorra' , 'capital' => 'Andorra la Vieja', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Angola' , 'capital' => 'Luanda', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Antigua y Barbuda' , 'capital' => 'Saint John', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Arabia Saudita' , 'capital' => 'Riad', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Argelia' , 'capital' => 'Argel', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Argentina' , 'capital' => 'Buenos Aires', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Armenia' , 'capital' => 'Ereván', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Australia' , 'capital' => 'Canberra', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Austria' , 'capital' => 'Viena', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Azerbaiyán' , 'capital' => 'Bakú', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Bahamas' , 'capital' => 'Nasáu', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Bangladés' , 'capital' => 'Daca', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Barbados' , 'capital' => 'Bridgetown', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Baréin' , 'capital' => 'Manama', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Bélgica' , 'capital' => 'Bruselas', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Belice' , 'capital' => 'Belmopán', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Benín' , 'capital' => 'Porto-Novo', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Bielorrusia' , 'capital' => 'Minsk', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Birmania' , 'capital' => 'Naipyidó', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Bolivia' , 'capital' => 'Sucre', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Bosnia-Herzegovina' , 'capital' => 'Sarajevo', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Botsuana' , 'capital' => 'Gaborone', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Brasil' , 'capital' => 'Brasilia', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Brunéi' , 'capital' => 'Bandar Seri Begawan', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Bulgaria' , 'capital' => 'Sofía', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Burkina Faso' , 'capital' => 'Uagadugú', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Burundi' , 'capital' => 'Buyumbura', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Bután' , 'capital' => 'Thimphu', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Cabo Verde' , 'capital' => 'Praia', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Camboya' , 'capital' => 'Nom Pen', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Camerún' , 'capital' => 'Yaundé', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Canadá' , 'capital' => 'Ottawa', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Catar' , 'capital' => 'Doha', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Chad' , 'capital' => 'Yamena', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Chile' , 'capital' => 'Santiago', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'China' , 'capital' => 'Pekín', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Chipre' , 'capital' => 'Nicosia', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Colombia' , 'capital' => 'Bogotá', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Comoras' , 'capital' => 'Moroni', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Congo' , 'capital' => 'Brazzaville', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Corea del Norte' , 'capital' => 'Pionyang', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Corea del Sur' , 'capital' => 'Seúl', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Costa de Marfil' , 'capital' => 'Yamusukro', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Costa Rica' , 'capital' => 'San José', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Croacia' , 'capital' => 'Zagreb', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Cuba' , 'capital' => 'La Habana', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Dinamarca' , 'capital' => 'Copenhague', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Dominica' , 'capital' => 'Roseau', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Ecuador' , 'capital' => 'Quito', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Egipto' , 'capital' => 'El Cairo', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'El Salvador' , 'capital' => 'San Salvador', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Emiratos Árabes Unidos' , 'capital' => 'Abu Dabi', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Eritrea' , 'capital' => 'Asmara', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Eslovaquia' , 'capital' => 'Bratislava', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Eslovenia' , 'capital' => 'Liubliana', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'España' , 'capital' => 'Madrid', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Estados Unidos' , 'capital' => 'Washington D. C.', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Estonia' , 'capital' => 'Tallin', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Etiopía' , 'capital' => 'Adís Abeba', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Filipinas' , 'capital' => 'Manila', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Finlandia' , 'capital' => 'Helsinki', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Fiyi' , 'capital' => 'Suva', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Francia' , 'capital' => 'París', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Gabón' , 'capital' => 'Libreville', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Gambia' , 'capital' => 'Banjul', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Georgia' , 'capital' => 'Tiflis', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Ghana' , 'capital' => 'Accra', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Granada' , 'capital' => 'Saint George', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Grecia' , 'capital' => 'Atenas', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Guatemala' , 'capital' => 'Guatemala', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Guinea' , 'capital' => 'Conakri', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Guinea Ecuatorial' , 'capital' => 'Malabo', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Guinea-Bisáu' , 'capital' => 'Bisáu', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Guyana' , 'capital' => 'Georgetown', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Haití' , 'capital' => 'Puerto Príncipe', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Honduras' , 'capital' => 'Tegucigalpa', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Hungría' , 'capital' => 'Budapest', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'India' , 'capital' => 'Nueva Delhi', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Indonesia' , 'capital' => 'Yakarta', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Inglaterra' , 'capital' => 'Londres', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Irak' , 'capital' => 'Bagdad', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Irán' , 'capital' => 'Teherán', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Irlanda' , 'capital' => 'Dublín', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Islandia' , 'capital' => 'Reikiavik', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Islas Marshall' , 'capital' => 'Majuro', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Islas Salomón' , 'capital' => 'Honiara', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Israel' , 'capital' => 'Jerusalén', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Italia' , 'capital' => 'Roma', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Jamaica' , 'capital' => 'Kingston', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Japón' , 'capital' => 'Tokio', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Jordania' , 'capital' => 'Amán', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Kazajistán' , 'capital' => 'Astaná', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Kenia' , 'capital' => 'Nairobi', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Kirguistán' , 'capital' => 'Biskek', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Kiribati' , 'capital' => 'Tarawa', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Kosovo' , 'capital' => 'Pristina', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Kuwait' , 'capital' => 'Kuwait City', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Laos' , 'capital' => 'Vientián', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Lesoto' , 'capital' => 'Maseru', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Letonia' , 'capital' => 'Riga', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Líbano' , 'capital' => 'Beirut', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Liberia' , 'capital' => 'Monrovia', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Libia' , 'capital' => 'Trípoli', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Liechtenstein' , 'capital' => 'Vaduz', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Lituania' , 'capital' => 'Vilna', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Luxemburgo' , 'capital' => 'Luxemburgo', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Macedonia' , 'capital' => 'Skopie', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Madagascar' , 'capital' => 'Antananarivo', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Malasia' , 'capital' => 'Kuala Lumpur', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Malaui' , 'capital' => 'Lilongüe', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Maldivas' , 'capital' => 'Malé', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Malí' , 'capital' => 'Bamako', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Malta' , 'capital' => 'La Valeta', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Marruecos' , 'capital' => 'Rabat', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Mauricio' , 'capital' => 'Port Louis', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Mauritania' , 'capital' => 'Nuakchot', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'México' , 'capital' => 'México', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Micronesia' , 'capital' => 'Palikir', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Moldavia' , 'capital' => 'Chisináu', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Mónaco' , 'capital' => 'Mónaco', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Mongolia' , 'capital' => 'Ulán Bator', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Montenegro' , 'capital' => 'Podgorica', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Mozambique' , 'capital' => 'Maputo', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Namibia' , 'capital' => 'Windhoek', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Nauru' , 'capital' => 'Yaren', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Nepal' , 'capital' => 'Katmandú', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Nicaragua' , 'capital' => 'Managua', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Níger' , 'capital' => 'Niamey', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Nigeria' , 'capital' => 'Abuya', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Noruega' , 'capital' => 'Oslo', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Nueva Zelanda' , 'capital' => 'Wellington', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Omán' , 'capital' => 'Mascate', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Países Bajos' , 'capital' => 'Ámsterdam', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Pakistán' , 'capital' => 'Islamabad', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Palaos' , 'capital' => 'Melekeok', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Palestina' , 'capital' => 'Jerusalén Este', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Panamá' , 'capital' => 'Panamá', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Papúa Nueva Guinea' , 'capital' => 'Puerto Moresby', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Paraguay' , 'capital' => 'Asunción', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Perú' , 'capital' => 'Lima', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Polonia' , 'capital' => 'Varsovia', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Portugal' , 'capital' => 'Lisboa', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Reino Unido' , 'capital' => 'Londres', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'República Centroafricana' , 'capital' => 'Bangui', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'República Checa' , 'capital' => 'Praga', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'República Democrática del Congo' , 'capital' => 'Kinsasa', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'República Dominicana' , 'capital' => 'Santo Domingo', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Ruanda' , 'capital' => 'Kigali', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Rumania' , 'capital' => 'Bucarest', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Rusia' , 'capital' => 'Moscú', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Samoa' , 'capital' => 'Apia', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'San Cristóbal y Nieves' , 'capital' => 'Basseterre', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'San Marino' , 'capital' => 'San Marino', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'San Vicente y las Granadinas' , 'capital' => 'Kingstown', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Santa Lucía' , 'capital' => 'Castries', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Santo Tomé y Príncipe' , 'capital' => 'Santo Tomé', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Senegal' , 'capital' => 'Dakar', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Serbia' , 'capital' => 'Belgrado', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Seychelles' , 'capital' => 'Victoria', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Sierra Leona' , 'capital' => 'Freetown', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Singapur' , 'capital' => 'Singapur', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Siria' , 'capital' => 'Damasco', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Somalia' , 'capital' => 'Mogadiscio', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Sri Lanka' , 'capital' => 'Sri Jayawardenapura Kotte', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Suazilandia' , 'capital' => 'Mbabane', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Sudáfrica' , 'capital' => 'Pretoria', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Sudán' , 'capital' => 'Jartum', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Sudán del Sur' , 'capital' => 'Yuba', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Suecia' , 'capital' => 'Estocolmo', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Suiza' , 'capital' => 'Berna', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Surinam' , 'capital' => 'Paramaribo', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Tailandia' , 'capital' => 'Bangkok', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Taiwán' , 'capital' => 'Taipéi', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Tanzania' , 'capital' => 'Dodoma', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Tayikistán' , 'capital' => 'Dusambé', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Timor Oriental' , 'capital' => 'Dili', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Togo' , 'capital' => 'Lomé', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Tonga' , 'capital' => 'Nukualofa', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Trinidad y Tobago' , 'capital' => 'Puerto España', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Túnez' , 'capital' => 'Túnez', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Turkmenistán' , 'capital' => 'Asjabad', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Turquía' , 'capital' => 'Ankara', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Tuvalu' , 'capital' => 'Funafuti', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Ucrania' , 'capital' => 'Kiev', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Uganda' , 'capital' => 'Kampala', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Uruguay' , 'capital' => 'Montevideo', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Uzbekistán' , 'capital' => 'Taskent', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Vanuatu' , 'capital' => 'Port Vila', 'continente' => 'Oceanía' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Vaticano' , 'capital' => 'Vaticano', 'continente' => 'Europa' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Venezuela' , 'capital' => 'Caracas', 'continente' => 'América' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Vietnam' , 'capital' => 'Hanói', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Yemen' , 'capital' => 'Saná', 'continente' => 'Asia' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Yibuti' , 'capital' => 'Yibuti', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Zambia' , 'capital' => 'Lusaka', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ],
        [ 'nombre' => 'Zimbabue' , 'capital' => 'Harare', 'continente' => 'África' , 'moneda' => '', 'activo' => 1 ]
      ];

      foreach ($paises as $pais) {

        Pais::create($pais);
      }
    }
}
