<html>
    <head>
        <title></title>
    </head>
    <body>
        <table>
            <thead>
                <tr>
                    <th>numreg</th>
                    <th>rut</th>
                    <th>razsoc</th>
                    <th>giro</th>
                    <th>comuna</th>
                    <th>ciudad</th>
                    <th>dir</th>
                    <th>email</th>
                    <th>fono</th>
                    <th>formapago</th>
                    <th>tipodoc</th>
                    <th>numfact</th>
                    <th>vendedor</th>
                    <th>fecha</th>
                    <th>vencimie</th>
                    <th>dctotipo</th>
                    <th>dctopje</th>
                    <th>codigo</th>
                    <th>descrip</th>
                    <th>cantidad</th>
                    <th>precunit</th>
                    <th>descto</th>
                    <th>descrip2</th>
                    <th>tipodesp</th>
                    <th>indtras</th>
                    <th>observacion</th>
                    <th>razonref</th>
                    <th>tipodocref</th>
                    <th>numdocref</th>
                    <th>fechadocref</th>
                    <th>exento</th>
                    <th>dctoto</th>
                    <th>unmed</th>
                    <th>unmed</th>
                    <th>impto</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>numreg</td>
                    <td>rut</td>
                    <td>razsoc</td>
                    <td>giro</td>
                    <td>comuna</td>
                    <td>ciudad</td>
                    <td>dir</td>
                    <td>email</td>
                    <td>fono</td>
                    <td>formapago</td>
                    <td>tipodoc</td>
                    <td>numfact</td>
                    <td>vendedor</td>
                    <td>fecha</td>
                    <td>vencimie</td>
                    <td>dctotipo</td>
                    <td>dctopje</td>
                    <td>codigo</td>
                    <td>descrip</td>
                    <td>cantidad</td>
                    <td>precunit</td>
                    <td>descto</td>
                    <td>descrip2</td>
                    <td>tipodesp</td>
                    <td>indtras</td>
                    <td>observacion</td>
                    <td>razonref</td>
                    <td>tipodocref</td>
                    <td>numdocref</td>
                    <td>fechadocref</td>
                    <td>exento</td>
                    <td>dctoto</td>
                    <td>unmed</td>
                    <td>unmed</td>
                    <td>impto</td>
                </tr>
            </tbody>
        </table>
    </body>
</html>
